name: pred6dof
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.1.19=hecd8cb5_0
  - certifi=2020.12.5=py39h6e9494a_1
  - cycler=0.10.0=py_2
  - freetype=2.10.4=h4cff582_1
  - jpeg=9d=hbcb3906_0
  - kiwisolver=1.3.1=py39hedf5dff_1
  - lcms2=2.11=h11f7e16_1
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libcxx=11.0.1=habf9029_0
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_17
  - libgfortran5=9.3.0=h6c81a4c_17
  - liblapack=3.9.0=7_openblas
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.2.0=h355d032_0
  - libwebp-base=1.1.0=hbcb3906_3
  - llvm-openmp=11.0.1=h7c73e74_0
  - lz4-c=1.9.3=h046ec9c_0
  - matplotlib=3.3.3=py39h6e9494a_0
  - matplotlib-base=3.3.3=py39hfe19100_0
  - ncurses=6.2=h2e338ed_4
  - numpy=1.19.5=py39he588a01_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1i=h35c211d_0
  - pandas=1.2.1=py39h089d6f7_0
  - patsy=0.5.1=py_0
  - pillow=8.1.0=py39hc06e9b5_1
  - pip=21.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.9.1=h1d169a7_3_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2020.5=pyhd8ed1ab_0
  - readline=8.0=h0678c8f_2
  - scipy=1.6.0=py39hca3e1c3_0
  - setuptools=51.3.3=py39hecd8cb5_4
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h17101e1_0
  - statsmodels=0.12.1=py39hae3b40e_2
  - tk=8.6.10=h0419947_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py39hcbf5805_1
  - tzdata=2020f=he74cb21_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.8=hf387650_1
  - pip:
    - filterpy==1.4.5
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyquaternion==0.9.9
prefix: /usr/local/Caskroom/miniconda/base/envs/pred6dof
